import React, { useState } from 'react';
import { videoAPI } from '../services/api';
import './ClaimsList.css';

function ClaimItem({ claim, index, type, videoId }) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  const [recheckLoading, setRecheckLoading] = useState(false);
  const [recheckResult, setRecheckResult] = useState(null);
  const [errorReported, setErrorReported] = useState(false);
  const [showThumbsUp, setShowThumbsUp] = useState(false);
  
  // Debug logging for each claim
  console.log(`🔍 ClaimItem [${type}] - videoId:`, videoId, 'Will show recheck button?', !!videoId);
  
  const handleCopy = (e) => {
    e.stopPropagation(); // Don't trigger expand/collapse
    
    // Format the claim data for copying
    const formattedText = `
📋 CLAIM:
"${claim.claim}"

⏱️ TIMESTAMP: ${claim.timestamp}

✅ VERDICT: ${claim.verdict}

📝 ANALYSIS:
${claim.explanation}

${claim.sources && claim.sources.length > 0 ? `
🔗 SOURCES:
${claim.sources.map(s => `• ${s}`).join('\n')}
` : ''}

💡 CONFIDENCE: ${claim.confidence || 'Not specified'}

---
Generated by BS Detector - https://bs-detector-transcriber.vercel.app
    `.trim();
    
    navigator.clipboard.writeText(formattedText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };
  
  const handleRecheck = async (e) => {
    e.stopPropagation(); // Don't trigger expand/collapse
    
    // Validate videoId before proceeding
    if (!videoId) {
      console.error('❌ Cannot re-check: videoId is missing!', { videoId });
      alert('Unable to re-check this claim. Please refresh the page and try again.');
      return;
    }
    
    setRecheckLoading(true);
    
    try {
      console.log('🔍 Re-checking claim...', { videoId, claim: claim.claim.substring(0, 50) + '...' });
      
      // Call API to re-fact-check this specific claim
      const response = await videoAPI.recheckClaim(videoId, {
        claim: claim.claim,
        timestamp: claim.timestamp,
        original_verdict: claim.verdict,
        context: claim.explanation
      });
      
      console.log('✅ Re-check result:', response.data);
      setRecheckResult(response.data.result);
      
      // Auto-expand to show results
      setExpanded(true);
    } catch (error) {
      console.error('❌ Re-check failed:', error);
      console.error('❌ Error response:', error.response);
      console.error('❌ Error data:', error.response?.data);
      
      let errorMessage = 'Failed to re-check claim. ';
      
      if (error.response?.data?.error) {
        errorMessage += error.response.data.error;
      } else if (error.message) {
        errorMessage += error.message;
      } else {
        errorMessage += 'Unknown error occurred.';
      }
      
      // Check for specific Claude API errors
      if (errorMessage.includes('model') || errorMessage.includes('404')) {
        errorMessage += '\n\n🔧 The AI model may need updating. Please contact support or try again later.';
      }
      
      alert(errorMessage);
    } finally {
      setRecheckLoading(false);
    }
  };
  
  const handleReportError = async (e) => {
    e.stopPropagation();
    
    if (errorReported) return; // Already reported
    
    try {
      // Get user email if available (for anonymous users)
      const userEmail = localStorage.getItem('user_email') || '';
      
      await videoAPI.reportClaimError({
        video_id: videoId || 'anonymous',
        claim_text: claim.claim,
        claim_verdict: claim.verdict,
        reason: 'User reported as incorrect',
        user_email: userEmail
      });
      
      // Show thumbs-up animation
      setShowThumbsUp(true);
      setErrorReported(true);
      
      // Hide animation after 2 seconds
      setTimeout(() => {
        setShowThumbsUp(false);
      }, 2000);
      
    } catch (error) {
      console.error('❌ Error reporting claim:', error);
      alert(`Failed to report error: ${error.response?.data?.error || error.message}`);
    }
  };
  
  const typeConfig = {
    verified: {
      icon: '✅',
      color: 'green',
      label: 'VERIFIED'
    },
    opinion: {
      icon: '🔮',
      color: 'purple',
      label: 'OPINION'
    },
    uncertain: {
      icon: '⚠️',
      color: 'orange',
      label: 'UNCERTAIN'
    },
    false: {
      icon: '❌',
      color: 'red',
      label: 'FALSE'
    }
  };
  
  const config = typeConfig[type] || typeConfig.uncertain;
  
  return (
    <div className={`claim-item ${config.color} ${expanded ? 'expanded' : ''} ${errorReported ? 'error-reported' : ''}`}>
      <div className="claim-header" onClick={() => setExpanded(!expanded)}>
        <div className="claim-left">
          <span className="claim-icon">{config.icon}</span>
          <span className="claim-timestamp">{claim.timestamp}</span>
          <span className={`claim-verdict ${config.color}`}>{config.label}</span>
        </div>
        <div className="claim-actions">
          <button 
            className={`claim-copy ${copied ? 'copied' : ''}`}
            onClick={handleCopy}
            title="Copy claim details"
          >
            {copied ? '✓ Copied!' : '📋 Copy'}
          </button>
          {videoId && (
            <button 
              className={`claim-recheck ${recheckLoading ? 'loading' : ''}`}
              onClick={handleRecheck}
              disabled={recheckLoading}
              title="Re-verify this claim with deeper analysis"
            >
              {recheckLoading ? '⏳' : '🔄'}
            </button>
          )}
          <button className="claim-expand">
            {expanded ? '▼' : '▶'}
          </button>
        </div>
      </div>
      
      {/* Thumbs-up animation overlay */}
      {showThumbsUp && (
        <div className="thumbs-up-animation">
          <div className="thumbs-up-icon">👍</div>
          <div className="thumbs-up-text">Thanks for the feedback!</div>
        </div>
      )}
      
      <div className="claim-text">
        "{claim.claim}"
      </div>
      
      {expanded && (
        <div className="claim-details">
          <div className="claim-explanation">
            <h4>Analysis:</h4>
            <p>{claim.explanation}</p>
          </div>
          
          {claim.confidence && (
            <div className="claim-confidence">
              <strong>Confidence:</strong> <span className={`confidence-badge ${claim.confidence.toLowerCase()}`}>{claim.confidence}</span>
            </div>
          )}
          
          {claim.sources && claim.sources.length > 0 && (
            <div className="claim-sources">
              <h4>Sources:</h4>
              <ul>
                {claim.sources.map((source, idx) => (
                  <li key={idx}>
                    {source.startsWith('http') ? (
                      <a href={source} target="_blank" rel="noopener noreferrer">
                        {source}
                      </a>
                    ) : (
                      source
                    )}
                  </li>
                ))}
              </ul>
            </div>
          )}
          
          {/* Show re-check results if available */}
          {recheckResult && (() => {
            // Helper function to get confidence change icon
            const getConfidenceIcon = (original, updated) => {
              const levels = { 'Low': 1, 'Medium': 2, 'High': 3 };
              const origLevel = levels[original] || 2;
              const updLevel = levels[updated] || 2;
              
              if (updLevel > origLevel) return ' ⬆️';
              if (updLevel < origLevel) return ' ⬇️';
              return ' ✓';
            };
            
            const confidenceChanged = claim.confidence !== recheckResult.confidence;
            const originalConfidence = claim.confidence || 'Medium';
            
            return (
              <div className="recheck-result">
                <div className="recheck-header">
                  <strong>🔍 Deep Re-check Results:</strong>
                  {recheckResult.changed && (
                    <span className="verdict-changed">⚠️ Verdict Changed!</span>
                  )}
                </div>
                
                {/* COMPARISON TABLE */}
                <div className="recheck-comparison-table">
                  <div className="comparison-row">
                    <div className="comparison-label"></div>
                    <div className="comparison-original-header">ORIGINAL</div>
                    <div className="comparison-arrow"></div>
                    <div className="comparison-updated-header">UPDATED</div>
                  </div>
                  
                  <div className="comparison-row">
                    <div className="comparison-label">Verdict:</div>
                    <div className="comparison-original">
                      <span className={`claim-verdict ${type}`}>
                        {claim.verdict}
                      </span>
                    </div>
                    <div className="comparison-arrow">→</div>
                    <div className="comparison-updated">
                      <span className={`claim-verdict ${recheckResult.verdict.toLowerCase()} ${recheckResult.changed ? 'changed' : 'same'}`}>
                        {recheckResult.verdict}
                        {recheckResult.changed ? ' ⚠️' : ' ✓'}
                      </span>
                    </div>
                  </div>
                  
                  <div className="comparison-row">
                    <div className="comparison-label">Confidence:</div>
                    <div className="comparison-original">
                      <span className={`confidence-badge ${originalConfidence.toLowerCase()}`}>
                        {originalConfidence}
                      </span>
                    </div>
                    <div className="comparison-arrow">→</div>
                    <div className="comparison-updated">
                      <span className={`confidence-badge ${recheckResult.confidence?.toLowerCase()}`}>
                        {recheckResult.confidence}
                        {getConfidenceIcon(originalConfidence, recheckResult.confidence)}
                      </span>
                    </div>
                  </div>
                </div>
                
                <div className="recheck-explanation">
                  <strong>Updated Analysis:</strong>
                  <p>{recheckResult.explanation}</p>
                </div>
                
                {recheckResult.correction_notes && (
                  <div className="recheck-notes">
                    <strong>Corrections Made:</strong>
                    <p>{recheckResult.correction_notes}</p>
                  </div>
                )}
                
                {recheckResult.sources && recheckResult.sources.length > 0 && (
                  <div className="recheck-sources">
                    <strong>Additional Sources:</strong>
                    <ul>
                      {recheckResult.sources.map((source, i) => (
                        <li key={i}>
                          <a href={source} target="_blank" rel="noopener noreferrer">{source}</a>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            );
          })()}
          
          {/* Report Error - subtle, low hierarchy */}
          <div className="claim-report-section">
            <button 
              className={`claim-report-error ${errorReported ? 'reported' : ''}`}
              onClick={handleReportError}
              disabled={errorReported}
              title="Report this claim as incorrect"
            >
              {errorReported ? '✓ Reported' : 'Report as incorrect'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function ClaimsList({ data, videoId }) {
  const [filter, setFilter] = useState('all');
  
  // Debug logging
  console.log('🔍 ClaimsList - videoId:', videoId);
  console.log('🔍 ClaimsList - videoId type:', typeof videoId);
  console.log('🔍 ClaimsList - Should show recheck button?', !!videoId);
  
  if (!data) return null;
  
  const verifiedClaims = data.verified_claims || [];
  const opinionClaims = data.opinion_claims || [];
  const uncertainClaims = data.uncertain_claims || [];
  const falseClaims = data.false_claims || [];
  
  const allClaims = [
    ...verifiedClaims.map(c => ({ ...c, type: 'verified' })),
    ...opinionClaims.map(c => ({ ...c, type: 'opinion' })),
    ...uncertainClaims.map(c => ({ ...c, type: 'uncertain' })),
    ...falseClaims.map(c => ({ ...c, type: 'false' }))
  ];
  
  const filteredClaims = filter === 'all' 
    ? allClaims 
    : allClaims.filter(c => c.type === filter);
  
  if (allClaims.length === 0) {
    return (
      <div className="claims-list">
        <h2>Claims Analysis</h2>
        <p className="no-claims">No specific claims detected in this video.</p>
      </div>
    );
  }
  
  return (
    <div className="claims-list">
      <div className="claims-header">
        <h2>Claims Detected ({allClaims.length})</h2>
        
        <div className="claims-filter">
          <button 
            className={filter === 'all' ? 'active' : ''} 
            onClick={() => setFilter('all')}
          >
            All ({allClaims.length})
          </button>
          <button 
            className={filter === 'verified' ? 'active' : ''} 
            onClick={() => setFilter('verified')}
          >
            ✅ Verified ({verifiedClaims.length})
          </button>
          <button 
            className={filter === 'opinion' ? 'active' : ''} 
            onClick={() => setFilter('opinion')}
          >
            🔮 Opinion ({opinionClaims.length})
          </button>
          <button 
            className={filter === 'uncertain' ? 'active' : ''} 
            onClick={() => setFilter('uncertain')}
          >
            ⚠️ Uncertain ({uncertainClaims.length})
          </button>
          <button 
            className={filter === 'false' ? 'active' : ''} 
            onClick={() => setFilter('false')}
          >
            ❌ False ({falseClaims.length})
          </button>
        </div>
      </div>
      
      <div className="claims-container">
        {filteredClaims.length > 0 ? (
          filteredClaims.map((claim, index) => (
            <ClaimItem 
              key={index} 
              claim={claim} 
              index={index} 
              type={claim.type}
              videoId={videoId}
            />
          ))
        ) : (
          <p className="no-claims">No claims match the selected filter.</p>
        )}
      </div>
    </div>
  );
}

export default ClaimsList;

